name = "codecritic"
pages_build_output_dir = ".svelte-kit/cloudflare"

compatibility_date = "2025-01-16"
compatibility_flags = ["nodejs_compat"]

[env.preview]
compatibility_date = "2025-01-16"
compatibility_flags = ["nodejs_compat"]
