name = "codecritic"
pages_build_output_dir = ".svelte-kit/cloudflare"

compatibility_date = "2024-02-23"
compatibility_flags = ["nodejs_compat"]

[vars]
NODE_VERSION = "20"

[env.preview]
compatibility_date = "2024-02-23"
compatibility_flags = ["nodejs_compat"]
